name: Auto Key Checker

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  check-keys:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история для rebase + merge
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync latest main  # Фикс non-fast-forward
        run: |
          git config pull.rebase true
          git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Download Xray linux amd64
        run: |
          curl -L "https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip" -o xray.zip
          unzip -o xray.zip
          chmod +x xray

      - name: Run Checker Script
        run: python main.py
        timeout-minutes: 340
        env:
          PYTHONUNBUFFERED: 1

      - name: Commit & Push Results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Auto-update checked keys [${{ github.run_id }}]"
          file_pattern: "checked/*"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          push_options: '--force-with-lease'  # Безопасный force на случай редких гонок
      - name: Send to Telegram
        run: |
          find . -maxdepth 2 -name "*.txt" -exec curl -v -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -F document=@{} https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument \;
